/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 10.3.0-1ubuntu1~20.10 -fPIC -Os) */

(* top =  1  *)
(* src = "pixelState.v:30" *)
module pixelState(clk, reset, erase, expose, read1, read2, read3, read4, convert);
  (* src = "pixelState.v:145" *)
  wire [31:0] _000_;
  (* src = "pixelState.v:62" *)
  wire _001_;
  (* src = "pixelState.v:62" *)
  wire _002_;
  (* src = "pixelState.v:145" *)
  wire [2:0] _003_;
  (* src = "pixelState.v:62" *)
  wire _004_;
  (* src = "pixelState.v:62" *)
  wire _005_;
  (* src = "pixelState.v:62" *)
  wire _006_;
  (* src = "pixelState.v:62" *)
  wire _007_;
  (* src = "pixelState.v:145" *)
  wire [2:0] _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  (* src = "pixelState.v:145" *)
  wire _202_;
  (* src = "pixelState.v:145" *)
  wire _203_;
  (* src = "pixelState.v:145" *)
  wire _204_;
  (* src = "pixelState.v:145" *)
  wire _205_;
  (* src = "pixelState.v:145" *)
  wire _206_;
  (* src = "pixelState.v:145" *)
  wire _207_;
  (* src = "pixelState.v:145" *)
  wire _208_;
  (* src = "pixelState.v:145" *)
  wire _209_;
  (* src = "pixelState.v:145" *)
  wire _210_;
  (* src = "pixelState.v:145" *)
  wire _211_;
  (* src = "pixelState.v:145" *)
  wire _212_;
  (* src = "pixelState.v:145" *)
  wire _213_;
  (* src = "pixelState.v:145" *)
  wire _214_;
  (* src = "pixelState.v:145" *)
  wire _215_;
  (* src = "pixelState.v:145" *)
  wire _216_;
  (* src = "pixelState.v:145" *)
  wire _217_;
  (* src = "pixelState.v:145" *)
  wire _218_;
  (* src = "pixelState.v:145" *)
  wire _219_;
  (* src = "pixelState.v:145" *)
  wire _220_;
  (* src = "pixelState.v:145" *)
  wire _221_;
  (* src = "pixelState.v:145" *)
  wire _222_;
  (* src = "pixelState.v:145" *)
  wire _223_;
  (* src = "pixelState.v:145" *)
  wire _224_;
  (* src = "pixelState.v:145" *)
  wire _225_;
  (* src = "pixelState.v:145" *)
  wire _226_;
  (* src = "pixelState.v:145" *)
  wire _227_;
  (* src = "pixelState.v:145" *)
  wire _228_;
  (* src = "pixelState.v:145" *)
  wire _229_;
  (* src = "pixelState.v:145" *)
  wire _230_;
  (* src = "pixelState.v:145" *)
  wire _231_;
  (* src = "pixelState.v:145" *)
  wire _232_;
  (* src = "pixelState.v:145" *)
  wire _233_;
  (* src = "pixelState.v:62" *)
  wire _234_;
  (* src = "pixelState.v:62" *)
  wire _235_;
  (* src = "pixelState.v:145" *)
  wire _236_;
  (* src = "pixelState.v:145" *)
  wire _237_;
  (* src = "pixelState.v:145" *)
  wire _238_;
  (* src = "pixelState.v:62" *)
  wire _239_;
  (* src = "pixelState.v:62" *)
  wire _240_;
  (* src = "pixelState.v:62" *)
  wire _241_;
  (* src = "pixelState.v:62" *)
  wire _242_;
  (* src = "pixelState.v:145" *)
  wire _243_;
  (* src = "pixelState.v:145" *)
  wire _244_;
  (* src = "pixelState.v:145" *)
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  (* src = "pixelState.v:31" *)
  wire _258_;
  (* src = "pixelState.v:58" *)
  wire _259_;
  (* src = "pixelState.v:58" *)
  wire _260_;
  (* src = "pixelState.v:58" *)
  wire _261_;
  (* src = "pixelState.v:58" *)
  wire _262_;
  (* src = "pixelState.v:58" *)
  wire _263_;
  (* src = "pixelState.v:58" *)
  wire _264_;
  (* src = "pixelState.v:58" *)
  wire _265_;
  (* src = "pixelState.v:58" *)
  wire _266_;
  (* src = "pixelState.v:58" *)
  wire _267_;
  (* src = "pixelState.v:58" *)
  wire _268_;
  (* src = "pixelState.v:58" *)
  wire _269_;
  (* src = "pixelState.v:58" *)
  wire _270_;
  (* src = "pixelState.v:58" *)
  wire _271_;
  (* src = "pixelState.v:58" *)
  wire _272_;
  (* src = "pixelState.v:58" *)
  wire _273_;
  (* src = "pixelState.v:58" *)
  wire _274_;
  (* src = "pixelState.v:58" *)
  wire _275_;
  (* src = "pixelState.v:58" *)
  wire _276_;
  (* src = "pixelState.v:58" *)
  wire _277_;
  (* src = "pixelState.v:58" *)
  wire _278_;
  (* src = "pixelState.v:58" *)
  wire _279_;
  (* src = "pixelState.v:58" *)
  wire _280_;
  (* src = "pixelState.v:58" *)
  wire _281_;
  (* src = "pixelState.v:58" *)
  wire _282_;
  (* src = "pixelState.v:58" *)
  wire _283_;
  (* src = "pixelState.v:58" *)
  wire _284_;
  (* src = "pixelState.v:58" *)
  wire _285_;
  (* src = "pixelState.v:58" *)
  wire _286_;
  (* src = "pixelState.v:58" *)
  wire _287_;
  (* src = "pixelState.v:58" *)
  wire _288_;
  (* src = "pixelState.v:58" *)
  wire _289_;
  (* src = "pixelState.v:58" *)
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  wire _468_;
  wire _469_;
  wire _470_;
  wire _471_;
  wire _472_;
  wire _473_;
  wire _474_;
  wire _475_;
  wire _476_;
  wire _477_;
  wire _478_;
  wire _479_;
  wire _480_;
  wire _481_;
  wire _482_;
  wire _483_;
  wire _484_;
  wire _485_;
  wire _486_;
  (* src = "pixelState.v:57" *)
  wire _487_;
  (* src = "pixelState.v:57" *)
  wire _488_;
  (* src = "pixelState.v:57" *)
  wire _489_;
  (* src = "pixelState.v:57" *)
  wire _490_;
  (* src = "pixelState.v:57" *)
  wire _491_;
  (* src = "pixelState.v:57" *)
  wire _492_;
  wire _493_;
  wire _494_;
  wire _495_;
  wire _496_;
  wire _497_;
  wire _498_;
  wire _499_;
  wire _500_;
  wire _501_;
  wire _502_;
  wire _503_;
  wire _504_;
  wire _505_;
  wire _506_;
  wire _507_;
  wire _508_;
  wire _509_;
  wire _510_;
  wire _511_;
  wire _512_;
  wire _513_;
  wire _514_;
  wire _515_;
  wire _516_;
  wire _517_;
  wire _518_;
  wire _519_;
  wire _520_;
  wire _521_;
  wire _522_;
  wire _523_;
  wire _524_;
  wire _525_;
  wire _526_;
  wire _527_;
  wire _528_;
  wire _529_;
  wire _530_;
  wire _531_;
  wire _532_;
  wire _533_;
  wire _534_;
  wire _535_;
  wire _536_;
  wire _537_;
  wire _538_;
  wire _539_;
  wire _540_;
  wire _541_;
  wire _542_;
  wire _543_;
  wire _544_;
  wire _545_;
  wire _546_;
  wire _547_;
  wire _548_;
  (* src = "pixelState.v:31" *)
  input clk;
  (* src = "pixelState.v:39" *)
  output convert;
  (* src = "pixelState.v:58" *)
  wire [31:0] counter;
  (* src = "pixelState.v:33" *)
  output erase;
  (* src = "pixelState.v:34" *)
  output expose;
  (* src = "pixelState.v:57" *)
  wire [2:0] next_state;
  (* src = "pixelState.v:35" *)
  output read1;
  (* src = "pixelState.v:36" *)
  output read2;
  (* src = "pixelState.v:37" *)
  output read3;
  (* src = "pixelState.v:38" *)
  output read4;
  (* src = "pixelState.v:32" *)
  input reset;
  (* src = "pixelState.v:57" *)
  wire [2:0] state;
  IVX1_CV _549_ (
    .A(_490_),
    .Y(_483_)
  );
  IVX1_CV _550_ (
    .A(_248_),
    .Y(_484_)
  );
  IVX1_CV _551_ (
    .A(_259_),
    .Y(_485_)
  );
  IVX1_CV _552_ (
    .A(_284_),
    .Y(_486_)
  );
  IVX1_CV _553_ (
    .A(_489_),
    .Y(_291_)
  );
  IVX1_CV _554_ (
    .A(_258_),
    .Y(_252_)
  );
  NRX1_CV _555_ (
    .A(_490_),
    .B(_491_),
    .Y(_292_)
  );
  NDX1_CV _556_ (
    .A(_492_),
    .B(_292_),
    .Y(_293_)
  );
  IVX1_CV _557_ (
    .A(_293_),
    .Y(_240_)
  );
  ANX1_CV _558_ (
    .A(_483_),
    .B(_491_),
    .Y(_294_)
  );
  NDX1_CV _559_ (
    .A(_492_),
    .B(_294_),
    .Y(_295_)
  );
  IVX1_CV _560_ (
    .A(_295_),
    .Y(_242_)
  );
  NDX1_CV _561_ (
    .A(_248_),
    .B(_292_),
    .Y(_296_)
  );
  IVX1_CV _562_ (
    .A(_296_),
    .Y(_234_)
  );
  NDX1_CV _563_ (
    .A(_490_),
    .B(_491_),
    .Y(_297_)
  );
  ORX1_CV _564_ (
    .A(_484_),
    .B(_297_),
    .Y(_298_)
  );
  IVX1_CV _565_ (
    .A(_298_),
    .Y(_239_)
  );
  NRX1_CV _566_ (
    .A(_483_),
    .B(_491_),
    .Y(_299_)
  );
  NDX1_CV _567_ (
    .A(_492_),
    .B(_299_),
    .Y(_300_)
  );
  IVX1_CV _568_ (
    .A(_300_),
    .Y(_241_)
  );
  NDX1_CV _569_ (
    .A(_248_),
    .B(_299_),
    .Y(_301_)
  );
  IVX1_CV _570_ (
    .A(_301_),
    .Y(_235_)
  );
  ORX1_CV _571_ (
    .A(_248_),
    .B(_297_),
    .Y(_302_)
  );
  ANX1_CV _572_ (
    .A(_485_),
    .B(_302_),
    .Y(_202_)
  );
  ANX1_CV _573_ (
    .A(_259_),
    .B(_270_),
    .Y(_303_)
  );
  NRX1_CV _574_ (
    .A(_485_),
    .B(_270_),
    .Y(_304_)
  );
  EOX1_CV _575_ (
    .A(_259_),
    .B(_270_),
    .Y(_305_)
  );
  ANX1_CV _576_ (
    .A(_302_),
    .B(_305_),
    .Y(_213_)
  );
  ANX1_CV _577_ (
    .A(_281_),
    .B(_303_),
    .Y(_306_)
  );
  ORX1_CV _578_ (
    .A(_281_),
    .B(_303_),
    .Y(_307_)
  );
  NDX1_CV _579_ (
    .A(_302_),
    .B(_307_),
    .Y(_308_)
  );
  NRX1_CV _580_ (
    .A(_306_),
    .B(_308_),
    .Y(_224_)
  );
  ANX1_CV _581_ (
    .A(_284_),
    .B(_306_),
    .Y(_309_)
  );
  ORX1_CV _582_ (
    .A(_284_),
    .B(_306_),
    .Y(_310_)
  );
  NDX1_CV _583_ (
    .A(_302_),
    .B(_310_),
    .Y(_311_)
  );
  NRX1_CV _584_ (
    .A(_309_),
    .B(_311_),
    .Y(_227_)
  );
  ANX1_CV _585_ (
    .A(_285_),
    .B(_309_),
    .Y(_312_)
  );
  ORX1_CV _586_ (
    .A(_285_),
    .B(_309_),
    .Y(_313_)
  );
  NDX1_CV _587_ (
    .A(_302_),
    .B(_313_),
    .Y(_314_)
  );
  NRX1_CV _588_ (
    .A(_312_),
    .B(_314_),
    .Y(_228_)
  );
  ANX1_CV _589_ (
    .A(_286_),
    .B(_312_),
    .Y(_315_)
  );
  ORX1_CV _590_ (
    .A(_286_),
    .B(_312_),
    .Y(_316_)
  );
  NDX1_CV _591_ (
    .A(_302_),
    .B(_316_),
    .Y(_317_)
  );
  NRX1_CV _592_ (
    .A(_315_),
    .B(_317_),
    .Y(_229_)
  );
  ANX1_CV _593_ (
    .A(_287_),
    .B(_315_),
    .Y(_318_)
  );
  ORX1_CV _594_ (
    .A(_287_),
    .B(_315_),
    .Y(_319_)
  );
  NDX1_CV _595_ (
    .A(_302_),
    .B(_319_),
    .Y(_320_)
  );
  NRX1_CV _596_ (
    .A(_318_),
    .B(_320_),
    .Y(_230_)
  );
  ANX1_CV _597_ (
    .A(_288_),
    .B(_318_),
    .Y(_321_)
  );
  ORX1_CV _598_ (
    .A(_288_),
    .B(_318_),
    .Y(_322_)
  );
  NDX1_CV _599_ (
    .A(_302_),
    .B(_322_),
    .Y(_323_)
  );
  NRX1_CV _600_ (
    .A(_321_),
    .B(_323_),
    .Y(_231_)
  );
  ANX1_CV _601_ (
    .A(_289_),
    .B(_321_),
    .Y(_324_)
  );
  ORX1_CV _602_ (
    .A(_289_),
    .B(_321_),
    .Y(_325_)
  );
  NDX1_CV _603_ (
    .A(_302_),
    .B(_325_),
    .Y(_326_)
  );
  NRX1_CV _604_ (
    .A(_324_),
    .B(_326_),
    .Y(_232_)
  );
  ANX1_CV _605_ (
    .A(_290_),
    .B(_324_),
    .Y(_327_)
  );
  ORX1_CV _606_ (
    .A(_290_),
    .B(_324_),
    .Y(_328_)
  );
  NDX1_CV _607_ (
    .A(_302_),
    .B(_328_),
    .Y(_329_)
  );
  NRX1_CV _608_ (
    .A(_327_),
    .B(_329_),
    .Y(_233_)
  );
  ANX1_CV _609_ (
    .A(_260_),
    .B(_327_),
    .Y(_330_)
  );
  ORX1_CV _610_ (
    .A(_260_),
    .B(_327_),
    .Y(_331_)
  );
  NDX1_CV _611_ (
    .A(_302_),
    .B(_331_),
    .Y(_332_)
  );
  NRX1_CV _612_ (
    .A(_330_),
    .B(_332_),
    .Y(_203_)
  );
  ANX1_CV _613_ (
    .A(_261_),
    .B(_330_),
    .Y(_333_)
  );
  ORX1_CV _614_ (
    .A(_261_),
    .B(_330_),
    .Y(_334_)
  );
  NDX1_CV _615_ (
    .A(_302_),
    .B(_334_),
    .Y(_335_)
  );
  NRX1_CV _616_ (
    .A(_333_),
    .B(_335_),
    .Y(_204_)
  );
  ANX1_CV _617_ (
    .A(_262_),
    .B(_333_),
    .Y(_336_)
  );
  ORX1_CV _618_ (
    .A(_262_),
    .B(_333_),
    .Y(_337_)
  );
  NDX1_CV _619_ (
    .A(_302_),
    .B(_337_),
    .Y(_338_)
  );
  NRX1_CV _620_ (
    .A(_336_),
    .B(_338_),
    .Y(_205_)
  );
  ANX1_CV _621_ (
    .A(_263_),
    .B(_336_),
    .Y(_339_)
  );
  ORX1_CV _622_ (
    .A(_263_),
    .B(_336_),
    .Y(_340_)
  );
  NDX1_CV _623_ (
    .A(_302_),
    .B(_340_),
    .Y(_341_)
  );
  NRX1_CV _624_ (
    .A(_339_),
    .B(_341_),
    .Y(_206_)
  );
  ANX1_CV _625_ (
    .A(_264_),
    .B(_339_),
    .Y(_342_)
  );
  ORX1_CV _626_ (
    .A(_264_),
    .B(_339_),
    .Y(_343_)
  );
  NDX1_CV _627_ (
    .A(_302_),
    .B(_343_),
    .Y(_344_)
  );
  NRX1_CV _628_ (
    .A(_342_),
    .B(_344_),
    .Y(_207_)
  );
  ANX1_CV _629_ (
    .A(_265_),
    .B(_342_),
    .Y(_345_)
  );
  ORX1_CV _630_ (
    .A(_265_),
    .B(_342_),
    .Y(_346_)
  );
  NDX1_CV _631_ (
    .A(_302_),
    .B(_346_),
    .Y(_347_)
  );
  NRX1_CV _632_ (
    .A(_345_),
    .B(_347_),
    .Y(_208_)
  );
  ANX1_CV _633_ (
    .A(_266_),
    .B(_345_),
    .Y(_348_)
  );
  ORX1_CV _634_ (
    .A(_266_),
    .B(_345_),
    .Y(_349_)
  );
  NDX1_CV _635_ (
    .A(_302_),
    .B(_349_),
    .Y(_350_)
  );
  NRX1_CV _636_ (
    .A(_348_),
    .B(_350_),
    .Y(_209_)
  );
  ANX1_CV _637_ (
    .A(_267_),
    .B(_348_),
    .Y(_351_)
  );
  ORX1_CV _638_ (
    .A(_267_),
    .B(_348_),
    .Y(_352_)
  );
  NDX1_CV _639_ (
    .A(_302_),
    .B(_352_),
    .Y(_353_)
  );
  NRX1_CV _640_ (
    .A(_351_),
    .B(_353_),
    .Y(_210_)
  );
  ANX1_CV _641_ (
    .A(_268_),
    .B(_351_),
    .Y(_354_)
  );
  ORX1_CV _642_ (
    .A(_268_),
    .B(_351_),
    .Y(_355_)
  );
  NDX1_CV _643_ (
    .A(_302_),
    .B(_355_),
    .Y(_356_)
  );
  NRX1_CV _644_ (
    .A(_354_),
    .B(_356_),
    .Y(_211_)
  );
  ANX1_CV _645_ (
    .A(_269_),
    .B(_354_),
    .Y(_357_)
  );
  ORX1_CV _646_ (
    .A(_269_),
    .B(_354_),
    .Y(_358_)
  );
  NDX1_CV _647_ (
    .A(_302_),
    .B(_358_),
    .Y(_359_)
  );
  NRX1_CV _648_ (
    .A(_357_),
    .B(_359_),
    .Y(_212_)
  );
  ANX1_CV _649_ (
    .A(_271_),
    .B(_357_),
    .Y(_360_)
  );
  ORX1_CV _650_ (
    .A(_271_),
    .B(_357_),
    .Y(_361_)
  );
  NDX1_CV _651_ (
    .A(_302_),
    .B(_361_),
    .Y(_362_)
  );
  NRX1_CV _652_ (
    .A(_360_),
    .B(_362_),
    .Y(_214_)
  );
  ANX1_CV _653_ (
    .A(_272_),
    .B(_360_),
    .Y(_363_)
  );
  ORX1_CV _654_ (
    .A(_272_),
    .B(_360_),
    .Y(_364_)
  );
  NDX1_CV _655_ (
    .A(_302_),
    .B(_364_),
    .Y(_365_)
  );
  NRX1_CV _656_ (
    .A(_363_),
    .B(_365_),
    .Y(_215_)
  );
  ANX1_CV _657_ (
    .A(_273_),
    .B(_363_),
    .Y(_366_)
  );
  ORX1_CV _658_ (
    .A(_273_),
    .B(_363_),
    .Y(_367_)
  );
  NDX1_CV _659_ (
    .A(_302_),
    .B(_367_),
    .Y(_368_)
  );
  NRX1_CV _660_ (
    .A(_366_),
    .B(_368_),
    .Y(_216_)
  );
  ANX1_CV _661_ (
    .A(_274_),
    .B(_366_),
    .Y(_369_)
  );
  ORX1_CV _662_ (
    .A(_274_),
    .B(_366_),
    .Y(_370_)
  );
  NDX1_CV _663_ (
    .A(_302_),
    .B(_370_),
    .Y(_371_)
  );
  NRX1_CV _664_ (
    .A(_369_),
    .B(_371_),
    .Y(_217_)
  );
  ANX1_CV _665_ (
    .A(_275_),
    .B(_369_),
    .Y(_372_)
  );
  ORX1_CV _666_ (
    .A(_275_),
    .B(_369_),
    .Y(_373_)
  );
  NDX1_CV _667_ (
    .A(_302_),
    .B(_373_),
    .Y(_374_)
  );
  NRX1_CV _668_ (
    .A(_372_),
    .B(_374_),
    .Y(_218_)
  );
  ANX1_CV _669_ (
    .A(_276_),
    .B(_372_),
    .Y(_375_)
  );
  ORX1_CV _670_ (
    .A(_276_),
    .B(_372_),
    .Y(_376_)
  );
  NDX1_CV _671_ (
    .A(_302_),
    .B(_376_),
    .Y(_377_)
  );
  NRX1_CV _672_ (
    .A(_375_),
    .B(_377_),
    .Y(_219_)
  );
  ANX1_CV _673_ (
    .A(_277_),
    .B(_375_),
    .Y(_378_)
  );
  ORX1_CV _674_ (
    .A(_277_),
    .B(_375_),
    .Y(_379_)
  );
  NDX1_CV _675_ (
    .A(_302_),
    .B(_379_),
    .Y(_380_)
  );
  NRX1_CV _676_ (
    .A(_378_),
    .B(_380_),
    .Y(_220_)
  );
  ANX1_CV _677_ (
    .A(_278_),
    .B(_378_),
    .Y(_381_)
  );
  ORX1_CV _678_ (
    .A(_278_),
    .B(_378_),
    .Y(_382_)
  );
  NDX1_CV _679_ (
    .A(_302_),
    .B(_382_),
    .Y(_383_)
  );
  NRX1_CV _680_ (
    .A(_381_),
    .B(_383_),
    .Y(_221_)
  );
  ANX1_CV _681_ (
    .A(_279_),
    .B(_381_),
    .Y(_384_)
  );
  ORX1_CV _682_ (
    .A(_279_),
    .B(_381_),
    .Y(_385_)
  );
  NDX1_CV _683_ (
    .A(_302_),
    .B(_385_),
    .Y(_386_)
  );
  NRX1_CV _684_ (
    .A(_384_),
    .B(_386_),
    .Y(_222_)
  );
  ANX1_CV _685_ (
    .A(_280_),
    .B(_384_),
    .Y(_387_)
  );
  ORX1_CV _686_ (
    .A(_280_),
    .B(_384_),
    .Y(_388_)
  );
  NDX1_CV _687_ (
    .A(_302_),
    .B(_388_),
    .Y(_389_)
  );
  NRX1_CV _688_ (
    .A(_387_),
    .B(_389_),
    .Y(_223_)
  );
  NDX1_CV _689_ (
    .A(_282_),
    .B(_387_),
    .Y(_390_)
  );
  ORX1_CV _690_ (
    .A(_282_),
    .B(_387_),
    .Y(_391_)
  );
  ANX1_CV _691_ (
    .A(_302_),
    .B(_391_),
    .Y(_392_)
  );
  ANX1_CV _692_ (
    .A(_390_),
    .B(_392_),
    .Y(_225_)
  );
  ENX1_CV _693_ (
    .A(_283_),
    .B(_390_),
    .Y(_393_)
  );
  ANX1_CV _694_ (
    .A(_302_),
    .B(_393_),
    .Y(_226_)
  );
  NRX1_CV _695_ (
    .A(_262_),
    .B(_263_),
    .Y(_394_)
  );
  NRX1_CV _696_ (
    .A(_264_),
    .B(_265_),
    .Y(_395_)
  );
  ANX1_CV _697_ (
    .A(_394_),
    .B(_395_),
    .Y(_396_)
  );
  NRX1_CV _698_ (
    .A(_289_),
    .B(_290_),
    .Y(_397_)
  );
  NRX1_CV _699_ (
    .A(_260_),
    .B(_261_),
    .Y(_398_)
  );
  ANX1_CV _700_ (
    .A(_397_),
    .B(_398_),
    .Y(_399_)
  );
  ANX1_CV _701_ (
    .A(_396_),
    .B(_399_),
    .Y(_400_)
  );
  NRX1_CV _702_ (
    .A(_279_),
    .B(_280_),
    .Y(_401_)
  );
  NRX1_CV _703_ (
    .A(_282_),
    .B(_283_),
    .Y(_402_)
  );
  ANX1_CV _704_ (
    .A(_401_),
    .B(_402_),
    .Y(_403_)
  );
  NRX1_CV _705_ (
    .A(_275_),
    .B(_276_),
    .Y(_404_)
  );
  NRX1_CV _706_ (
    .A(_277_),
    .B(_278_),
    .Y(_405_)
  );
  ANX1_CV _707_ (
    .A(_404_),
    .B(_405_),
    .Y(_406_)
  );
  ANX1_CV _708_ (
    .A(_403_),
    .B(_406_),
    .Y(_407_)
  );
  NRX1_CV _709_ (
    .A(_271_),
    .B(_272_),
    .Y(_408_)
  );
  NRX1_CV _710_ (
    .A(_273_),
    .B(_274_),
    .Y(_409_)
  );
  ANX1_CV _711_ (
    .A(_408_),
    .B(_409_),
    .Y(_410_)
  );
  NRX1_CV _712_ (
    .A(_266_),
    .B(_267_),
    .Y(_411_)
  );
  NRX1_CV _713_ (
    .A(_268_),
    .B(_269_),
    .Y(_412_)
  );
  ANX1_CV _714_ (
    .A(_411_),
    .B(_412_),
    .Y(_413_)
  );
  ANX1_CV _715_ (
    .A(_410_),
    .B(_413_),
    .Y(_414_)
  );
  ANX1_CV _716_ (
    .A(_400_),
    .B(_414_),
    .Y(_415_)
  );
  ANX1_CV _717_ (
    .A(_407_),
    .B(_415_),
    .Y(_416_)
  );
  NDX1_CV _718_ (
    .A(_321_),
    .B(_416_),
    .Y(_417_)
  );
  NDX1_CV _719_ (
    .A(_248_),
    .B(_294_),
    .Y(_418_)
  );
  ANX1_CV _720_ (
    .A(_301_),
    .B(_418_),
    .Y(_419_)
  );
  NDX1_CV _721_ (
    .A(_301_),
    .B(_418_),
    .Y(_420_)
  );
  NDX1_CV _722_ (
    .A(_417_),
    .B(_420_),
    .Y(_421_)
  );
  ANX1_CV _723_ (
    .A(_295_),
    .B(_298_),
    .Y(_422_)
  );
  NDX1_CV _724_ (
    .A(_300_),
    .B(_422_),
    .Y(_423_)
  );
  NRX1_CV _725_ (
    .A(_285_),
    .B(_288_),
    .Y(_424_)
  );
  NRX1_CV _726_ (
    .A(_286_),
    .B(_287_),
    .Y(_425_)
  );
  ANX1_CV _727_ (
    .A(_424_),
    .B(_425_),
    .Y(_426_)
  );
  ANX1_CV _728_ (
    .A(_281_),
    .B(_486_),
    .Y(_427_)
  );
  ANX1_CV _729_ (
    .A(_304_),
    .B(_427_),
    .Y(_428_)
  );
  ANX1_CV _730_ (
    .A(_426_),
    .B(_428_),
    .Y(_429_)
  );
  NDX1_CV _731_ (
    .A(_416_),
    .B(_429_),
    .Y(_430_)
  );
  ANX1_CV _732_ (
    .A(_423_),
    .B(_430_),
    .Y(_431_)
  );
  ANX1_CV _733_ (
    .A(_492_),
    .B(_297_),
    .Y(_432_)
  );
  ORX1_CV _734_ (
    .A(_248_),
    .B(_432_),
    .Y(_433_)
  );
  NRX1_CV _735_ (
    .A(_292_),
    .B(_431_),
    .Y(_434_)
  );
  ANX1_CV _736_ (
    .A(_421_),
    .B(_433_),
    .Y(_435_)
  );
  NDX1_CV _737_ (
    .A(_434_),
    .B(_435_),
    .Y(_436_)
  );
  NDX1_CV _738_ (
    .A(_487_),
    .B(_436_),
    .Y(_437_)
  );
  ORX1_CV _739_ (
    .A(_417_),
    .B(_418_),
    .Y(_438_)
  );
  ANX1_CV _740_ (
    .A(_293_),
    .B(_296_),
    .Y(_439_)
  );
  ORX1_CV _741_ (
    .A(_430_),
    .B(_439_),
    .Y(_440_)
  );
  ANX1_CV _742_ (
    .A(_438_),
    .B(_440_),
    .Y(_441_)
  );
  NDX1_CV _743_ (
    .A(_437_),
    .B(_441_),
    .Y(_236_)
  );
  NDX1_CV _744_ (
    .A(_250_),
    .B(_417_),
    .Y(_442_)
  );
  NDX1_CV _745_ (
    .A(_420_),
    .B(_442_),
    .Y(_443_)
  );
  NDX1_CV _746_ (
    .A(_295_),
    .B(_296_),
    .Y(_444_)
  );
  NDX1_CV _747_ (
    .A(_430_),
    .B(_444_),
    .Y(_445_)
  );
  ANX1_CV _748_ (
    .A(_300_),
    .B(_445_),
    .Y(_446_)
  );
  NRX1_CV _749_ (
    .A(_300_),
    .B(_430_),
    .Y(_447_)
  );
  ORX1_CV _750_ (
    .A(_488_),
    .B(_447_),
    .Y(_448_)
  );
  NDX1_CV _751_ (
    .A(_293_),
    .B(_298_),
    .Y(_449_)
  );
  NDX1_CV _752_ (
    .A(_430_),
    .B(_449_),
    .Y(_450_)
  );
  ANX1_CV _753_ (
    .A(_433_),
    .B(_450_),
    .Y(_451_)
  );
  NDX1_CV _754_ (
    .A(_446_),
    .B(_451_),
    .Y(_452_)
  );
  NDX1_CV _755_ (
    .A(_448_),
    .B(_452_),
    .Y(_453_)
  );
  NDX1_CV _756_ (
    .A(_443_),
    .B(_453_),
    .Y(_237_)
  );
  ORX1_CV _757_ (
    .A(_251_),
    .B(_421_),
    .Y(_454_)
  );
  NDX1_CV _758_ (
    .A(_291_),
    .B(_430_),
    .Y(_455_)
  );
  NRX1_CV _759_ (
    .A(_291_),
    .B(_433_),
    .Y(_456_)
  );
  NRX1_CV _760_ (
    .A(_449_),
    .B(_456_),
    .Y(_457_)
  );
  NDX1_CV _761_ (
    .A(_446_),
    .B(_457_),
    .Y(_458_)
  );
  NDX1_CV _762_ (
    .A(_455_),
    .B(_458_),
    .Y(_459_)
  );
  NDX1_CV _763_ (
    .A(_454_),
    .B(_459_),
    .Y(_238_)
  );
  ORX1_CV _764_ (
    .A(_417_),
    .B(_419_),
    .Y(_460_)
  );
  EOX1_CV _765_ (
    .A(_490_),
    .B(_491_),
    .Y(_461_)
  );
  NRX1_CV _766_ (
    .A(_492_),
    .B(_461_),
    .Y(_462_)
  );
  NRX1_CV _767_ (
    .A(_432_),
    .B(_462_),
    .Y(_463_)
  );
  NDX1_CV _768_ (
    .A(_302_),
    .B(_419_),
    .Y(_464_)
  );
  NDX1_CV _769_ (
    .A(_463_),
    .B(_464_),
    .Y(_465_)
  );
  NDX1_CV _770_ (
    .A(_490_),
    .B(_465_),
    .Y(_466_)
  );
  ORX1_CV _771_ (
    .A(_246_),
    .B(_419_),
    .Y(_467_)
  );
  ORX1_CV _772_ (
    .A(_249_),
    .B(_302_),
    .Y(_468_)
  );
  ANX1_CV _773_ (
    .A(_467_),
    .B(_468_),
    .Y(_469_)
  );
  ANX1_CV _774_ (
    .A(_466_),
    .B(_469_),
    .Y(_470_)
  );
  ORX1_CV _775_ (
    .A(_430_),
    .B(_463_),
    .Y(_471_)
  );
  ANX1_CV _776_ (
    .A(_470_),
    .B(_471_),
    .Y(_472_)
  );
  NDX1_CV _777_ (
    .A(_460_),
    .B(_472_),
    .Y(_243_)
  );
  NDX1_CV _778_ (
    .A(_491_),
    .B(_465_),
    .Y(_473_)
  );
  ORX1_CV _779_ (
    .A(_247_),
    .B(_419_),
    .Y(_474_)
  );
  ORX1_CV _780_ (
    .A(_250_),
    .B(_302_),
    .Y(_475_)
  );
  ANX1_CV _781_ (
    .A(_474_),
    .B(_475_),
    .Y(_476_)
  );
  ANX1_CV _782_ (
    .A(_473_),
    .B(_476_),
    .Y(_477_)
  );
  ANX1_CV _783_ (
    .A(_471_),
    .B(_477_),
    .Y(_478_)
  );
  NDX1_CV _784_ (
    .A(_460_),
    .B(_478_),
    .Y(_244_)
  );
  NDX1_CV _785_ (
    .A(_492_),
    .B(_302_),
    .Y(_479_)
  );
  ORX1_CV _786_ (
    .A(_251_),
    .B(_302_),
    .Y(_480_)
  );
  ANX1_CV _787_ (
    .A(_479_),
    .B(_480_),
    .Y(_481_)
  );
  ANX1_CV _788_ (
    .A(_471_),
    .B(_481_),
    .Y(_482_)
  );
  NDX1_CV _789_ (
    .A(_460_),
    .B(_482_),
    .Y(_245_)
  );
  IVX1_CV _790_ (
    .A(_258_),
    .Y(_253_)
  );
  IVX1_CV _791_ (
    .A(_258_),
    .Y(_254_)
  );
  IVX1_CV _792_ (
    .A(_258_),
    .Y(_255_)
  );
  IVX1_CV _793_ (
    .A(_258_),
    .Y(_256_)
  );
  IVX1_CV _794_ (
    .A(_258_),
    .Y(_257_)
  );
  (* src = "pixelState.v:62" *)
  DFSRQNX1_CV _795_ (
    .CK(_543_),
    .D(_006_),
    .Q(read3),
    .QN(_493_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:62" *)
  DFSRQNX1_CV _796_ (
    .CK(_544_),
    .D(_007_),
    .Q(read4),
    .QN(_494_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:62" *)
  DFSRQNX1_CV _797_ (
    .CK(_545_),
    .D(_004_),
    .Q(read1),
    .QN(_495_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:62" *)
  DFSRQNX1_CV _798_ (
    .CK(_546_),
    .D(_005_),
    .Q(read2),
    .QN(_496_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:62" *)
  DFSRQNX1_CV _799_ (
    .CK(_547_),
    .D(_001_),
    .Q(erase),
    .QN(_497_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:62" *)
  DFSRQNX1_CV _800_ (
    .CK(_548_),
    .D(_002_),
    .Q(expose),
    .QN(_498_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _801_ (
    .CK(clk),
    .D(_008_[0]),
    .Q(state[0]),
    .QN(_499_),
    .R(1'h0),
    .S(reset)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _802_ (
    .CK(clk),
    .D(_008_[1]),
    .Q(state[1]),
    .QN(_500_),
    .R(1'h0),
    .S(reset)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _803_ (
    .CK(clk),
    .D(_008_[2]),
    .Q(state[2]),
    .QN(_501_),
    .R(1'h0),
    .S(reset)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _804_ (
    .CK(clk),
    .D(_003_[0]),
    .Q(next_state[0]),
    .QN(_502_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _805_ (
    .CK(clk),
    .D(_003_[1]),
    .Q(next_state[1]),
    .QN(_503_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _806_ (
    .CK(clk),
    .D(_003_[2]),
    .Q(next_state[2]),
    .QN(_504_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _807_ (
    .CK(clk),
    .D(_000_[0]),
    .Q(counter[0]),
    .QN(_505_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _808_ (
    .CK(clk),
    .D(_000_[1]),
    .Q(counter[1]),
    .QN(_506_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _809_ (
    .CK(clk),
    .D(_000_[2]),
    .Q(counter[2]),
    .QN(_507_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _810_ (
    .CK(clk),
    .D(_000_[3]),
    .Q(counter[3]),
    .QN(_508_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _811_ (
    .CK(clk),
    .D(_000_[4]),
    .Q(counter[4]),
    .QN(_509_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _812_ (
    .CK(clk),
    .D(_000_[5]),
    .Q(counter[5]),
    .QN(_510_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _813_ (
    .CK(clk),
    .D(_000_[6]),
    .Q(counter[6]),
    .QN(_511_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _814_ (
    .CK(clk),
    .D(_000_[7]),
    .Q(counter[7]),
    .QN(_512_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _815_ (
    .CK(clk),
    .D(_000_[8]),
    .Q(counter[8]),
    .QN(_513_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _816_ (
    .CK(clk),
    .D(_000_[9]),
    .Q(counter[9]),
    .QN(_514_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _817_ (
    .CK(clk),
    .D(_000_[10]),
    .Q(counter[10]),
    .QN(_515_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _818_ (
    .CK(clk),
    .D(_000_[11]),
    .Q(counter[11]),
    .QN(_516_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _819_ (
    .CK(clk),
    .D(_000_[12]),
    .Q(counter[12]),
    .QN(_517_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _820_ (
    .CK(clk),
    .D(_000_[13]),
    .Q(counter[13]),
    .QN(_518_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _821_ (
    .CK(clk),
    .D(_000_[14]),
    .Q(counter[14]),
    .QN(_519_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _822_ (
    .CK(clk),
    .D(_000_[15]),
    .Q(counter[15]),
    .QN(_520_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _823_ (
    .CK(clk),
    .D(_000_[16]),
    .Q(counter[16]),
    .QN(_521_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _824_ (
    .CK(clk),
    .D(_000_[17]),
    .Q(counter[17]),
    .QN(_522_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _825_ (
    .CK(clk),
    .D(_000_[18]),
    .Q(counter[18]),
    .QN(_523_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _826_ (
    .CK(clk),
    .D(_000_[19]),
    .Q(counter[19]),
    .QN(_524_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _827_ (
    .CK(clk),
    .D(_000_[20]),
    .Q(counter[20]),
    .QN(_525_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _828_ (
    .CK(clk),
    .D(_000_[21]),
    .Q(counter[21]),
    .QN(_526_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _829_ (
    .CK(clk),
    .D(_000_[22]),
    .Q(counter[22]),
    .QN(_527_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _830_ (
    .CK(clk),
    .D(_000_[23]),
    .Q(counter[23]),
    .QN(_528_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _831_ (
    .CK(clk),
    .D(_000_[24]),
    .Q(counter[24]),
    .QN(_529_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _832_ (
    .CK(clk),
    .D(_000_[25]),
    .Q(counter[25]),
    .QN(_530_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _833_ (
    .CK(clk),
    .D(_000_[26]),
    .Q(counter[26]),
    .QN(_531_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _834_ (
    .CK(clk),
    .D(_000_[27]),
    .Q(counter[27]),
    .QN(_532_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _835_ (
    .CK(clk),
    .D(_000_[28]),
    .Q(counter[28]),
    .QN(_533_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _836_ (
    .CK(clk),
    .D(_000_[29]),
    .Q(counter[29]),
    .QN(_534_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _837_ (
    .CK(clk),
    .D(_000_[30]),
    .Q(counter[30]),
    .QN(_535_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:145" *)
  DFSRQNX1_CV _838_ (
    .CK(clk),
    .D(_000_[31]),
    .Q(counter[31]),
    .QN(_536_),
    .R(reset),
    .S(1'h0)
  );
  assign convert = 1'h0;
  assign _181_ = _499_;
  assign _186_ = _500_;
  assign _195_ = _501_;
  assign _178_ = _502_;
  assign _157_ = _503_;
  assign _167_ = _504_;
  assign _492_ = state[2];
  assign _005_ = _240_;
  assign _490_ = state[0];
  assign _491_ = state[1];
  assign _007_ = _242_;
  assign _248_ = _501_;
  assign _001_ = _234_;
  assign _004_ = _239_;
  assign _006_ = _241_;
  assign _002_ = _235_;
  assign _259_ = counter[0];
  assign _000_[0] = _202_;
  assign _270_ = counter[1];
  assign _000_[1] = _213_;
  assign _281_ = counter[2];
  assign _000_[2] = _224_;
  assign _284_ = counter[3];
  assign _000_[3] = _227_;
  assign _285_ = counter[4];
  assign _000_[4] = _228_;
  assign _286_ = counter[5];
  assign _000_[5] = _229_;
  assign _287_ = counter[6];
  assign _000_[6] = _230_;
  assign _288_ = counter[7];
  assign _000_[7] = _231_;
  assign _289_ = counter[8];
  assign _000_[8] = _232_;
  assign _290_ = counter[9];
  assign _000_[9] = _233_;
  assign _260_ = counter[10];
  assign _000_[10] = _203_;
  assign _261_ = counter[11];
  assign _000_[11] = _204_;
  assign _262_ = counter[12];
  assign _000_[12] = _205_;
  assign _263_ = counter[13];
  assign _000_[13] = _206_;
  assign _264_ = counter[14];
  assign _000_[14] = _207_;
  assign _265_ = counter[15];
  assign _000_[15] = _208_;
  assign _266_ = counter[16];
  assign _000_[16] = _209_;
  assign _267_ = counter[17];
  assign _000_[17] = _210_;
  assign _268_ = counter[18];
  assign _000_[18] = _211_;
  assign _269_ = counter[19];
  assign _000_[19] = _212_;
  assign _271_ = counter[20];
  assign _000_[20] = _214_;
  assign _272_ = counter[21];
  assign _000_[21] = _215_;
  assign _273_ = counter[22];
  assign _000_[22] = _216_;
  assign _274_ = counter[23];
  assign _000_[23] = _217_;
  assign _275_ = counter[24];
  assign _000_[24] = _218_;
  assign _276_ = counter[25];
  assign _000_[25] = _219_;
  assign _277_ = counter[26];
  assign _000_[26] = _220_;
  assign _278_ = counter[27];
  assign _000_[27] = _221_;
  assign _279_ = counter[28];
  assign _000_[28] = _222_;
  assign _280_ = counter[29];
  assign _000_[29] = _223_;
  assign _282_ = counter[30];
  assign _000_[30] = _225_;
  assign _283_ = counter[31];
  assign _000_[31] = _226_;
  assign _487_ = next_state[0];
  assign _003_[0] = _236_;
  assign _488_ = next_state[1];
  assign _250_ = _503_;
  assign _003_[1] = _237_;
  assign _489_ = next_state[2];
  assign _251_ = _504_;
  assign _003_[2] = _238_;
  assign _249_ = _502_;
  assign _246_ = _499_;
  assign _008_[0] = _243_;
  assign _247_ = _500_;
  assign _008_[1] = _244_;
  assign _008_[2] = _245_;
  assign _258_ = clk;
  assign _543_ = _252_;
  assign _544_ = _253_;
  assign _545_ = _254_;
  assign _546_ = _255_;
  assign _547_ = _256_;
  assign _548_ = _257_;
endmodule
